# azure-pipelines.yml  (Angular only)
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    clean: true

  - task: NodeTool@0
    displayName: 'Use Node 20.x'
    inputs:
      versionSpec: '20.x'

  - script: |
      node -v
      npm -v
    displayName: 'Show Node & npm versions'

  # If your Angular project is at repo root (as in your screenshot),
  # leave workingDirectory as "."
  # If it’s in a folder (e.g. ./frontend), set workingDirectory accordingly.

  - script: npm ci
    workingDirectory: .
    displayName: 'Install deps (npm ci)'

  - script: |
      if npm run | grep -q "^  build"; then
        echo "Running npm run build"
        npm run build
      else
        echo "No build script found. Using Angular CLI directly."
        npx @angular/cli@19 build --configuration=production
      fi
    workingDirectory: .
    displayName: 'Build Angular app'

  - script: |
      echo "Dist contents:"
      ls -la dist || true
    workingDirectory: .
    displayName: 'List dist output (debug)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifacts'
    inputs:
      PathtoPublish: 'dist'
      ArtifactName: 'web-dist'
      publishLocation: 'Container'
